<html>
	<head>
		<meta charset=utf-8>

		<link rel="stylesheet" type="text/css" href="css/base.css">
		<link rel="stylesheet" type="text/css" href="css/questionnaire.css">

		<!-- Google Login API -->
		<script src="https://apis.google.com/js/platform.js" async defer></script>
		<meta name="google-signin-client_id" content="282086877099-0tbur6mtoah3pb0co4ht3sooqkgi9612.apps.googleusercontent.com">

		<title>アンケート回答用ログイン</title>
	</head>

	<body>
		<header>
			<div class='header-inner'>
				Questionnaire
			</div>
		</header>
		
		<div id="contents">
			<form class="q-submit" method="POST" action="index.php?event=checkLogin">
				<div class="login-container">
					<p class="error">
						<?= nl2br(htmlspecialchars($view['error_message'])) ?>
					</p>
					<div class="input-container">
						<p>ユーザ名</p>
						<input type="text" name="username" placeholder="ユーザ名" required autoforcus>
					</div>
					<div class="input-container">
						<p>パスワード</p>
						<input type="password" name="password" placeholder="パスワード" required>
					</div>
				</div><br>
				<input class="submit" type="submit" value="ログイン">
			</form>

			<!-- SNS Login -->
			<script src="js/signin.js"></script>
			<div class="q-submit">
				<p>or</p>
				<div class="g-signin2" data-onsuccess="onSignIn"></div>
			</div>
		</div>
	</body>
</html>