<html>
	<head>
		<meta charset=utf-8>
		<link rel="stylesheet" type="text/css" href="css/base.css">
		<link rel="stylesheet" type="text/css" href="css/questionnaire.css">
		<title>アンケート回答用ログイン</title>
	</head>

	<body>
		<header>
			<div class='header-inner'>
				Questionnaire
			</div>
		</header>
		
		<div id="contents">
			<form class="q-submit" method="POST" action="index.php?event=checkLogin">
				<div class="login-container">
					<p class="error">
						<?= nl2br(htmlspecialchars($view['error_message'])) ?>
					</p>
					<div class="input-container">
						<p>ユーザ名</p>
						<input type="text" name="username" placeholder="ユーザ名" required autoforcus>
					</div>
					<div class="input-container">
						<p>パスワード</p>
						<input type="password" name="password" placeholder="パスワード" required>
					</div>
				</div><br>
				<input class="submit" type="submit" value="ログイン">
			</form>
		</div>
	</body>
</html>