<html>
	<head>
		<meta charset=utf-8>
		<link rel="stylesheet" type="text/css" href="css/base.css">
		<link rel="stylesheet" type="text/css" href="css/questionnaire.css">
		<title>アンケート調査の入力完了</title>
	</head>
	
	<body>
		<header>
			<div class='header-inner'>
				Questionnaire
			</div>
		</header>

		<div id="contents">
			<p class="attention-center splatoon">
				ごキョウリョクありがとうございました！<br>
				みんなのケッカもミてみよう！
			</p>

			<!-- 画面遷移 -->
			<div class="flex-wrapper">
				<div class='q-submit'>
					<form method="POST" action="index.php?event=showInputPage">
						<input class="submit" type="submit" value="入力画面に戻る">
					</form>
				</div>
				<div class='q-submit'>
					<form method="POST" action="index.php?event=showAll">
						<input class="friend-submit" type="submit" value="みんなの結果を見る">
					</form>
				</div>
			</div>
		</div>
	</body>
</html>