<html>
	<head>
		<meta charset='utf-8'>
		<link rel="stylesheet" type="text/css" href="base.css">
		<link rel="stylesheet" type="text/css" href="questionnaire.css">
		<title>みんなのアンケート調査の投票内容</title>
	</head>
	
	<body>

		<header>
			<div class='header-inner'>
				Questionnaire
			</div>
		</header>

		<div id="contents">
			<h3>みんなの回答内容</h3>

			<!-- 表形式の表示 -->
			<div id="gender_chart" class="pie-chart"></div>
			<div id="known_chart" class="pie-chart"></div>
			<div id="played_chart" class="pie-chart"></div>
			<div id="kind_chart" class="pie-chart"></div>
			<div id="salmonid_chart" class="bar-chart"></div>

			<!-- 画面遷移 -->
			<div class="clearfix">
				<div class='float-left'>
					<form method="POST" action="index.php?event=showInputPage">
						<input class="submit" type="submit" value="入力画面に戻る">
					</form>
				</div>
				<div class='float-right'>
					<form method="POST" action="index.php?event=download">
						<input class="friend-submit" type="submit" value="CSV形式でダウンロード">
					</form>
				</div>
			</div>
		</div>
	</body>
</html>