<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	</head>

	<body>
		<form name="submit_form" method="POST" action="javascript:void(0)">
			チャット
			<input type="text" id="submit-text" name="chattext" size="100" disabled>
			<input type="submit" id="submit" onclick="send_message()" value="送信" disabled>
		</form>

		<form name="logout_form" method="POST" action="index.php?event=logout">
			<input type="submit" value="ログアウト" >
		</form>

		<p id="result"></p>

		<!-- 以下, javascript -->
		<script type="text/javascript">

			// WebSocketオープン
			var ws = new WebSocket("ws://192.168.1.9:8080/talk");

			function send_message()
			{
				// チャットテキスト内の文字列を取得
				var val = document.submit_form.chattext.value;
				if (val == '')
					return;

				// ログイン時の名前と一緒に送信
				var name = "<?php echo htmlspecialchars($view['username']); ?>";
				ws.send(name + '> ' + val);

				// 送信後はチャットテキスト内のテキストを削除
				document.submit_form.chattext.value = '';
			}


			// WebSocketオープン時にコールバックするイベントリスナを登録
			ws.addEventListener("open",    

					function(e) {
							// WebSocketがオープンできたらコントロールを有効化
							document.getElementById("submit-text").disabled = false;
							document.getElementById("submit").disabled = false;
					}

			);


			// データ受信時にコールバックするイベントリスナを登録
			ws.addEventListener("message", 

					function(e) {

							// 受信結果を表示

							document.getElementById("result").innerHTML = 
									document.getElementById("result").innerHTML + e.data + "<br>";

					}

			);


			// WebSocketクローズ時にコールバックするイベントリスナを登録
			ws.addEventListener("close",   

					function(e) {

							// WebSocketクローズを知らせる

							document.getElementById("result").innerHTML = "接続を閉じました";

					}

			);
		</script>
	</body>
</html>