<html>
	<head>
		<title>アルバイト入力用ログイン</title>
	</head>
	<body>
		<center>
			<h1>アルバイト入力用ログイン</h1>
			<font color="red">
				<?= nl2br(htmlspecialchars($view['errorMessage'])) ?>
			</font>
			<form method="POST" action="index.php?event=checkLogin">
				ユーザ名:<input type="text" name="username"><br>
				パスワード:<input type="password" name="password"><br><br>
				<input type="submit" value="ログイン">
			</form>
		</center>
	</body>
</html>